DROP TABLE IF EXISTS ANALYTICS.SAAS_METRICS.MRR_SNAPSHOT;

DROP TABLE IF EXISTS ANALYTICS.SAAS_METRICS.DAILY_ACTIVITY_METRICS;

DROP TABLE IF EXISTS ANALYTICS.SAAS_METRICS.DAILY_REVENUE_METRICS;

DROP TABLE IF EXISTS ANALYTICS.SAAS_METRICS.TEST_TABLE;
