SELECT * FROM ANALYTICS.SAAS_METRICS.CHURN_ANALYSIS ORDER BY metric_date DESC;

SELECT * FROM ANALYTICS.SAAS_METRICS.ARPU_ANALYSIS ORDER BY snapshot_date DESC;

SELECT * FROM ANALYTICS.SAAS_METRICS.SUBSCRIPTION_GROWTH ORDER BY metric_date DESC;

SELECT * FROM ANALYTICS.SAAS_METRICS.MRR_TREND ORDER BY snapshot_date DESC;

SELECT * FROM ANALYTICS.SAAS_METRICS.ACTIVE_SUBS_TREND ORDER BY snapshot_date DESC;

SELECT * FROM ANALYTICS.SAAS_METRICS.MRR_CHANGE ORDER BY snapshot_date DESC;

SELECT * FROM ANALYTICS.SAAS_METRICS.BUSINESS_DASHBOARD ORDER BY metric_date DESC;
