CREATE OR REPLACE ICEBERG TABLE ANALYTICS.SAAS_METRICS.SUBSCRIPTION_KPIS_SNAPSHOT
CATALOG = databricks_unity_catalog_integration
CATALOG_TABLE_NAME ='subscription_kpis_snapshot'
AUTO_REFRESH = FALSE;               

DESC TABLE ANALYTICS.SAAS_METRICS.SUBSCRIPTION_KPIS_SNAPSHOT;

ALTER ICEBERG TABLE ANALYTICS.SAAS_METRICS.SUBSCRIPTION_KPIS_SNAPSHOT REFRESH;

SELECT
    * 
FROM 
    ANALYTICS.SAAS_METRICS.SUBSCRIPTION_KPIS_SNAPSHOT;
