CREATE OR REPLACE ICEBERG TABLE ANALYTICS.SAAS_METRICS.DAILY_ACTIVITY_METRICS
CATALOG = databricks_unity_catalog_integration
CATALOG_TABLE_NAME ='daily_activity_metrics'
AUTO_REFRESH = FALSE;               

ALTER ICEBERG TABLE ANALYTICS.SAAS_METRICS.DAILY_ACTIVITY_METRICS REFRESH;

DESC TABLE ANALYTICS.SAAS_METRICS.DAILY_ACTIVITY_METRICS;

SELECT
    * 
FROM 
    ANALYTICS.SAAS_METRICS.DAILY_ACTIVITY_METRICS;
