CREATE OR REPLACE VIEW ANALYTICS.SAAS_METRICS.ACTIVE_SUBS_TREND AS
SELECT
    snapshot_date,
    active_subscriptions
FROM
    ANALYTICS.SAAS_METRICS.SUBSCRIPTION_KPIS_SNAPSHOT
ORDER BY
    snapshot_date;
